#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Uplod.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Uplod_cshtml_ : System.Web.Mvc.WebViewPage<string>
    {
        public _Views_Shared_EditorTemplates_Uplod_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<input");

WriteLiteral(" type=\"file\"");

WriteAttribute("id", Tuple.Create(" id=\"", 33), Tuple.Create("\"", 44)
            
            #line 2 "..\..\Views\Shared\EditorTemplates\Uplod.cshtml"
, Tuple.Create(Tuple.Create("", 38), Tuple.Create<System.Object, System.Int32>(Model
            
            #line default
            #line hidden
, 38), false)
);

WriteLiteral(" class=\"Upload\"");

WriteAttribute("name", Tuple.Create(" name=\"", 60), Tuple.Create("\"", 73)
            
            #line 2 "..\..\Views\Shared\EditorTemplates\Uplod.cshtml"
, Tuple.Create(Tuple.Create("", 67), Tuple.Create<System.Object, System.Int32>(Model
            
            #line default
            #line hidden
, 67), false)
);

WriteLiteral("/>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
