#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkSample/Index.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkSample_Index_cshtml : System.Web.Mvc.WebViewPage<WorkSamplesPlugin.Areas.WorkSamples.Models.SampleWorkViewModel>
    {
        public _Areas_WorkSamples_Views_WorkSample_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
  
    ViewBag.Title = "نمونه کار";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_LayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
 using (Html.BeginForm("", "", FormMethod.Post,
                            new { enctype = "multipart/form-data"}))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding:25px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading text-right\"");

WriteLiteral(">دسته بندی</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"CategoryList\"");

WriteLiteral(">\r\n\r\n\r\n");

            
            #line 19 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Html.RenderAction("WorkCategoryRadioButton", "WorkCategory");
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n\r\n   " +
"         <div");

WriteLiteral(" id=\"tags\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding: 25px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading text-right\"");

WriteLiteral(">نوشته</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div>\r\n\r\n");

WriteLiteral("                        ");

            
            #line 37 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                       Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                       Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 42 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                             if (Model != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1469), Tuple.Create("\"", 1498)
            
            #line 44 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1477), Tuple.Create<System.Object, System.Int32>(Model.WorkCategoryId
            
            #line default
            #line hidden
, 1477), false)
);

WriteLiteral(" id=\"category\"");

WriteLiteral("/>\r\n");

            
            #line 45 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div>\r\n");

WriteLiteral("                                    ");

            
            #line 48 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                               Write(Html.LabelFor(model => model.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 49 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                               Write(Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 50 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 55 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.LabelFor(model => model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 56 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 57 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n\r\n                                </div>\r\n                            </div>\r\n" +
"\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 64 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.LabelFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 65 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 66 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 70 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.LabelFor(model => model.Image));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"Image\"");

WriteLiteral(" name=\"Image\"");

WriteLiteral(" />\r\n");

WriteLiteral("                                ");

            
            #line 72 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Image, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 76 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.LabelFor(model => model.DoTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 77 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.EditorFor(model => model.DoTime, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 78 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.DoTime, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ذخیره\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                        </div>\r\n\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n\r\n\r\n\r\n        </div>\r\n    </div>\r\n");

            
            #line 96 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 101 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 102 "..\..\Areas\WorkSamples\Views\WorkSample\Index.cshtml"
Write(Scripts.Render("~/bundles/PersianDateTimePicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n    <script>\r\n        $(function () {\r\n            var cat = $(\"#category" +
"\").val();\r\n\r\n            var elem = $(\"input[value=\" + cat + \"]\").prop(\"checked\"" +
", true);\r\n            console.log(elem);\r\n        });\r\n    </script>\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
