#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkSample/List.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkSample_List_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_WorkSamples_Views_WorkSample_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\WorkSamples\Views\WorkSample\List.cshtml"
  
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_LayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Areas\WorkSamples\Views\WorkSample\List.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\WorkSamples\Views\WorkSample\List.cshtml"
       Html.RenderAction("SampleWorkList", "WorkSample");
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Areas\WorkSamples\Views\WorkSample\List.cshtml"
Write(Scripts.Render("~/bundles/Pager"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Areas\WorkSamples\Views\WorkSample\List.cshtml"
Write(Scripts.Render("~/bundles/Admin"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
