#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
    using BaseMVC;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
    using MvcAjaxPager;
    
    #line default
    #line hidden
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkSample/SampleWorkList.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkSample_SampleWorkList_cshtml : System.Web.Mvc.WebViewPage<WorkSamplesPlugin.Areas.WorkSamples.Models.SampleWorkListViewModel>
    {
        public _Areas_WorkSamples_Views_WorkSample_SampleWorkList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"divtarget\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-bordered table-hover table-responsive table-striped tdCenter\"" +
"");

WriteLiteral(@">
        <tr>
            <th>
                نام
            </th>
            <th>
                دسته ی
            </th>
            <th>
                تصویر
            </th>
            <th>نمایش</th>
            <th>ویرایش</th>

            <th>حذف</th>
        </tr>

");

            
            #line 23 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
         foreach (var item in Model.WorkSamples)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
               Write(Html.DisplayFor(modelItem => item.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
               Write(Html.DisplayFor(modelItem => item.ParentName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td >\r\n                    <div");

WriteLiteral(" class=\"img\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"img-responsive\"");

WriteAttribute("src", Tuple.Create(" src=\"", 937), Tuple.Create("\"", 967)
            
            #line 34 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
, Tuple.Create(Tuple.Create("", 943), Tuple.Create<System.Object, System.Int32>(Url.Content(item.Image)
            
            #line default
            #line hidden
, 943), false)
);

WriteLiteral(" />\r\n                    </div>\r\n                </td>\r\n                <td>\r\n   " +
"                 <a");

WriteLiteral(" class=\"label label-success\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1096), Tuple.Create("\"", 1156)
            
            #line 38 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
, Tuple.Create(Tuple.Create("", 1103), Tuple.Create<System.Object, System.Int32>(Url.Action("Show", "WorkSample", new {id = item.Id})
            
            #line default
            #line hidden
, 1103), false)
);

WriteLiteral(">نمایش</a>\r\n                </td>\r\n                <td>\r\n                    <a");

WriteLiteral(" class=\"label label-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1264), Tuple.Create("\"", 1324)
            
            #line 41 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
, Tuple.Create(Tuple.Create("", 1271), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "WorkSample", new {id = item.Id})
            
            #line default
            #line hidden
, 1271), false)
);

WriteLiteral(">ویرایش</a>\r\n                </td>\r\n                <td>\r\n                    <a");

WriteLiteral(" class=\"label label-danger deleteBtn\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1442), Tuple.Create("\"", 1504)
            
            #line 44 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
, Tuple.Create(Tuple.Create("", 1449), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "WorkSample", new {id = item.Id})
            
            #line default
            #line hidden
, 1449), false)
);

WriteLiteral(">حذف</a>\r\n                </td>\r\n            </tr>\r\n");

            
            #line 47 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </table>\r\n    <div");

WriteLiteral(" id=\"pager\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Areas\WorkSamples\Views\WorkSample\SampleWorkList.cshtml"
   Write(Html.AjaxPager(Model.TotalItemCount, Model.PageSize, Model.CurrentPage, "SampleWorkList", "WorkSample", null,
        CustomePagerOptions.CustomePageOptions(), null, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
