#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkCategory/Index.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkCategory_Index_cshtml : System.Web.Mvc.WebViewPage<WorkSamplesPlugin.Areas.WorkSamples.Models.WorkCategoryViewModel>
    {
        public _Areas_WorkSamples_Views_WorkCategory_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Admin_LayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
 using (Html.BeginForm())
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding:25px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading text-right\"");

WriteLiteral(">دسته بندی</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"CategoryList\"");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\r\n");

            
            #line 17 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Html.RenderAction("List", "WorkCategory");
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n\r\n " +
"           <div");

WriteLiteral(" id=\"tags\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding: 25px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-primary\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading text-right\"");

WriteLiteral(">نوشته</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div>\r\n\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 39 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                       Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                       Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 41 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                             if (Model != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <input");

WriteLiteral(" id=\"parnet\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1372), Tuple.Create("\"", 1395)
            
            #line 43 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1380), Tuple.Create<System.Object, System.Int32>(Model.ParentId
            
            #line default
            #line hidden
, 1380), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral("/>\r\n");

            
            #line 44 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div>\r\n");

WriteLiteral("                                    ");

            
            #line 47 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                               Write(Html.LabelFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 48 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                               Write(Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 49 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 54 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.LabelFor(model => model.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 55 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 56 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n\r\n                                </div>\r\n                            </div>\r\n" +
"\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 63 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.LabelFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 64 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 65 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 69 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.LabelFor(model => model.KeyWord));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 70 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.EditorFor(model => model.KeyWord, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 71 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                           Write(Html.ValidationMessageFor(model => model.KeyWord, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label>زیر مجموعه</label>\r\n                   " +
"             <select");

WriteLiteral(" id=\"ParentId\"");

WriteLiteral(" name=\"ParentId\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">هیچکدام</option>\r\n                                </select>\r\n                   " +
"         </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"دخیره\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                        </div>\r\n\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n\r\n\r\n\r\n        </div>\r\n    </div>\r\n");

            
            #line 96 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 101 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 102 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
Write(Scripts.Render("~/bundles/TagScript"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 4243), Tuple.Create("\"", 4276)
, Tuple.Create(Tuple.Create("", 4249), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/sendAjaxScript.js")
, 4249), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function() {\r\n\r\n            \r\n            var" +
" select = $(\"#ParentId\");\r\n            var url = \'");

            
            #line 109 "..\..\Areas\WorkSamples\Views\WorkCategory\Index.cshtml"
                  Write(Url.Action("CategorySelect", "WorkCategory"));

            
            #line default
            #line hidden
WriteLiteral(@"';
            SendAjax(url, undefined, AjaxOption.Get, function(d) {
                for (var i = 0; i < d.length; i++) {
                    var opt = $(""<option value='"" + d[i].Id + ""'>"" + d[i].Name + ""</option>"");
                    select.append(opt);
                }
                select.removeClass(""hidden"");

                var vl = $(""#parnet"").val();
                if (vl == undefined || vl.trim().length==0)
                    vl = 1;
                select.val(vl);
            });

            
        });
    </script>
");

});

WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
