#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkCategory/List.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkCategory_List_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<WorkSamplesPlugin.Areas.WorkSamples.Models.WorkCategoryViewModel>>
    {
        public _Areas_WorkSamples_Views_WorkCategory_List_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral("  class=\"table table-bordered table-responsive table-hover table-striped tdCenter" +
"\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 6 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        \r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 10 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
       Write(Html.DisplayNameFor(model => model.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 15 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
       Write(Html.DisplayFor(modelItem => item.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n       \r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
       Write(item.ParentName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n            ");

WriteLiteral("\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 727), Tuple.Create("\"", 785)
            
            #line 26 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
, Tuple.Create(Tuple.Create("", 734), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit","WorkCategory",new {id=item.Id})
            
            #line default
            #line hidden
, 734), false)
);

WriteLiteral(" class=\"label label-success\"");

WriteLiteral(">ویرایش</a>      |\r\n            ");

WriteLiteral("\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 956), Tuple.Create("\"", 1016)
            
            #line 28 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
, Tuple.Create(Tuple.Create("", 963), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete","WorkCategory",new {id=item.Id})
            
            #line default
            #line hidden
, 963), false)
);

WriteLiteral(" class=\"label label-danger deleteBtn\"");

WriteLiteral(">جذف</a>\r\n\r\n           \r\n        </td>\r\n    </tr>\r\n");

            
            #line 33 "..\..\Areas\WorkSamples\Views\WorkCategory\List.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
