#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/WorkCategory/WorkCategoryRadioButton.cshtml")]
    public partial class _Areas_WorkSamples_Views_WorkCategory_WorkCategoryRadioButton_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<FrameWork.Application.SelectList>>
    {
        public _Areas_WorkSamples_Views_WorkCategory_WorkCategoryRadioButton_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul>\r\n");

            
            #line 4 "..\..\Areas\WorkSamples\Views\WorkCategory\WorkCategoryRadioButton.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\WorkSamples\Views\WorkCategory\WorkCategoryRadioButton.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n");

WriteLiteral("            ");

            
            #line 7 "..\..\Areas\WorkSamples\Views\WorkCategory\WorkCategoryRadioButton.cshtml"
       Write(Html.RadioButton("WorkCategoryId", item.Id));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 7 "..\..\Areas\WorkSamples\Views\WorkCategory\WorkCategoryRadioButton.cshtml"
                                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </li>\r\n");

            
            #line 9 "..\..\Areas\WorkSamples\Views\WorkCategory\WorkCategoryRadioButton.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
