#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<!DOCTYPE html>
<!--[if lt IE 7]>      <html class=""no-js lt-ie9 lt-ie8 lt-ie7""> <![endif]-->
<!--[if IE 7]>         <html class=""no-js lt-ie9 lt-ie8""> <![endif]-->
<!--[if IE 8]>         <html class=""no-js lt-ie9""> <![endif]-->
<!--[if gt IE 8]><!-->
<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n\r\n    <title>");

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
      Write(Model.SeoModel.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 402), Tuple.Create("\"", 436)
            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 412), Tuple.Create<System.Object, System.Int32>(Model.SeoModel.KeyWords
            
            #line default
            #line hidden
, 412), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 470), Tuple.Create("\"", 507)
            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 480), Tuple.Create<System.Object, System.Int32>(Model.SeoModel.Description
            
            #line default
            #line hidden
, 480), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n\r\n    <!-- Place favicon.ico and apple-touch-icon.png in the root directory --" +
">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 696), Tuple.Create("\"", 738)
            
            #line 18 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 703), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/bootstrap.css")
            
            #line default
            #line hidden
, 703), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 768), Tuple.Create("\"", 811)
            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 775), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/animations.css")
            
            #line default
            #line hidden
, 775), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 841), Tuple.Create("\"", 878)
            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/main.css")
            
            #line default
            #line hidden
, 848), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"top\"");

WriteLiteral(@"></div>
    <!--[if lt IE 7]>
        <p class=""chromeframe"">You are using an <strong>outdated</strong> browser. Please <a href=""http://browsehappy.com/"">upgrade your browser</a> or <a href=""http://www.google.com/chromeframe/?redirect=true"">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->

");

            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
       Html.RenderAction("Menu", "Home"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
       Html.RenderAction("Footer", "Home");
            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
