#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Footer.cshtml")]
    public partial class _Views_Shared_Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Footer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<footer");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"bg-color0\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-4 block widget_text\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"block widget_tweet\"");

WriteLiteral(">\r\n                    <h3>Our Twitter</h3>\r\n                    <div");

WriteLiteral(" class=\"twitter\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n\r\n\r\n            <div");

WriteLiteral(" class=\"block col-sm-4 subscribe\"");

WriteLiteral(">\r\n                <h3>\r\n                    در ارتباط باشید\r\n                </h" +
"3>\r\n                <p>از این پس کارهای شما را ما انجام می دهیم</p>\r\n           " +
"     <form");

WriteLiteral(" id=\"signup\"");

WriteLiteral(" action=\"/\"");

WriteLiteral(" method=\"get\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" name=\"email\"");

WriteLiteral(" id=\"mailchimp_email\"");

WriteLiteral(" type=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"your@email.com\"");

WriteLiteral(">\r\n                    </div>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"theme_btn\"");

WriteLiteral(">ارسال</button>\r\n                    <div");

WriteLiteral(" id=\"response\"");

WriteLiteral("></div>\r\n                </form>\r\n            </div>\r\n\r\n\r\n            <div");

WriteLiteral(" class=\"block col-sm-4\"");

WriteLiteral(">\r\n                <h3>\r\n                    Flickr ما\r\n                </h3>\r\n  " +
"              <ul");

WriteLiteral(" id=\"flickr\"");

WriteLiteral("></ul>\r\n            </div>\r\n\r\n\r\n        </div>\r\n    </div>\r\n</footer>\r\n\r\n<section" +
"");

WriteLiteral(" id=\"copyleft\"");

WriteLiteral(" class=\"dark_section\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"background-color: blue; height: 350px;\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"background-color: red; height: 350px;\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"background-color: yellow; height: 350px;\"");

WriteLiteral("></div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n\r\n                    کپی رایت@2015 تمام حقوق مادی و معنوی این سایت متعلق به گ" +
"روه  ما میباشد\r\n                    <a");

WriteLiteral(" href=\"http://www.komakfori.org\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("></a>\r\n                </p>\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</" +
"section>\r\n\r\n</div><!-- EOF #box_wrap -->\r\n\r\n<div");

WriteLiteral(" id=\"gallery_container\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"preloader\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"preloaderimg\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2204), Tuple.Create("\"", 2252)
            
            #line 73 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2210), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/respond.min.js")
            
            #line default
            #line hidden
, 2210), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2272), Tuple.Create("\"", 2325)
            
            #line 74 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2278), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/placeholders.min.js")
            
            #line default
            #line hidden
, 2278), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2345), Tuple.Create("\"", 2399)
            
            #line 75 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2351), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery-1.10.2.min.js")
            
            #line default
            #line hidden
, 2351), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2419), Tuple.Create("\"", 2469)
            
            #line 76 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/bootstrap.min.js")
            
            #line default
            #line hidden
, 2425), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2489), Tuple.Create("\"", 2537)
            
            #line 77 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2495), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/hoverIntent.js")
            
            #line default
            #line hidden
, 2495), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2557), Tuple.Create("\"", 2603)
            
            #line 78 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2563), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/superfish.js")
            
            #line default
            #line hidden
, 2563), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2623), Tuple.Create("\"", 2677)
            
            #line 79 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2629), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.actual.min.js")
            
            #line default
            #line hidden
, 2629), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2697), Tuple.Create("\"", 2752)
            
            #line 80 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2703), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.elastislide.js")
            
            #line default
            #line hidden
, 2703), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2772), Tuple.Create("\"", 2830)
            
            #line 81 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2778), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.flexslider-min.js")
            
            #line default
            #line hidden
, 2778), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2850), Tuple.Create("\"", 2905)
            
            #line 82 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2856), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.prettyPhoto.js")
            
            #line default
            #line hidden
, 2856), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2925), Tuple.Create("\"", 2979)
            
            #line 83 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 2931), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.easing.1.3.js")
            
            #line default
            #line hidden
, 2931), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2999), Tuple.Create("\"", 3051)
            
            #line 84 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3005), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.ui.totop.js")
            
            #line default
            #line hidden
, 3005), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3071), Tuple.Create("\"", 3126)
            
            #line 85 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3077), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.isotope.min.js")
            
            #line default
            #line hidden
, 3077), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3146), Tuple.Create("\"", 3206)
            
            #line 86 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3152), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.easypiechart.min.js")
            
            #line default
            #line hidden
, 3152), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3226), Tuple.Create("\"", 3278)
            
            #line 87 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3232), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jflickrfeed.min.js")
            
            #line default
            #line hidden
, 3232), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3298), Tuple.Create("\"", 3348)
            
            #line 88 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3304), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.sticky.js")
            
            #line default
            #line hidden
, 3304), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3368), Tuple.Create("\"", 3421)
            
            #line 89 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3374), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/owl.carousel.min.js")
            
            #line default
            #line hidden
, 3374), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3441), Tuple.Create("\"", 3499)
            
            #line 90 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3447), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.nicescroll.min.js")
            
            #line default
            #line hidden
, 3447), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3519), Tuple.Create("\"", 3581)
            
            #line 91 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3525), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.fractionslider.min.js")
            
            #line default
            #line hidden
, 3525), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3601), Tuple.Create("\"", 3657)
            
            #line 92 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3607), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.scrollTo-min.js")
            
            #line default
            #line hidden
, 3607), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3677), Tuple.Create("\"", 3736)
            
            #line 93 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3683), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.localscroll-min.js")
            
            #line default
            #line hidden
, 3683), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3756), Tuple.Create("\"", 3814)
            
            #line 94 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3762), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/vendor/jquery.parallax-1.1.3.js")
            
            #line default
            #line hidden
, 3762), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3834), Tuple.Create("\"", 3880)
            
            #line 95 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3840), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/jquery.tweet.min.js")
            
            #line default
            #line hidden
, 3840), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3900), Tuple.Create("\"", 3937)
            
            #line 96 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3906), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/plugins.js")
            
            #line default
            #line hidden
, 3906), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3957), Tuple.Create("\"", 3991)
            
            #line 97 "..\..\Views\Shared\Footer.cshtml"
, Tuple.Create(Tuple.Create("", 3963), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/main.js")
            
            #line default
            #line hidden
, 3963), false)
);

WriteLiteral("></script>\r\n\r\n<!-- Map Scripts -->\r\n</body>\r\n</html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
