#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Header.cshtml")]
    public partial class _Views_Shared_Header_cshtml : System.Web.Mvc.WebViewPage<PluginBase.SeoModel>
    {
        public _Views_Shared_Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<!DOCTYPE html>
<!--[if lt IE 7]>      <html class=""no-js lt-ie9 lt-ie8 lt-ie7""> <![endif]-->
<!--[if IE 7]>         <html class=""no-js lt-ie9 lt-ie8""> <![endif]-->
<!--[if IE 8]>         <html class=""no-js lt-ie9""> <![endif]-->
<!--[if gt IE 8]><!-->
<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n\r\n    <title>");

            
            #line 12 "..\..\Views\Shared\Header.cshtml"
      Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 421), Tuple.Create("\"", 446)
            
            #line 13 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 431), Tuple.Create<System.Object, System.Int32>(Model.KeyWords
            
            #line default
            #line hidden
, 431), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 480), Tuple.Create("\"", 508)
            
            #line 14 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 490), Tuple.Create<System.Object, System.Int32>(Model.Description
            
            #line default
            #line hidden
, 490), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n\r\n    <!-- Place favicon.ico and apple-touch-icon.png in the root directory --" +
">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 697), Tuple.Create("\"", 739)
            
            #line 19 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 704), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/bootstrap.css")
            
            #line default
            #line hidden
, 704), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 769), Tuple.Create("\"", 812)
            
            #line 20 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 776), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/animations.css")
            
            #line default
            #line hidden
, 776), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 842), Tuple.Create("\"", 879)
            
            #line 21 "..\..\Views\Shared\Header.cshtml"
, Tuple.Create(Tuple.Create("", 849), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/main.css")
            
            #line default
            #line hidden
, 849), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Shared\Header.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"top\"");

WriteLiteral(@"></div>
    <!--[if lt IE 7]>
        <p class=""chromeframe"">You are using an <strong>outdated</strong> browser. Please <a href=""http://browsehappy.com/"">upgrade your browser</a> or <a href=""http://www.google.com/chromeframe/?redirect=true"">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->

");

            
            #line 30 "..\..\Views\Shared\Header.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\Header.cshtml"
       Html.RenderAction("AdminMenu","Home"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n   \r\n\r\n");

        }
    }
}
#pragma warning restore 1591
