#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Menu.cshtml")]
    public partial class _Views_Shared_Menu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Menu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<section");

WriteLiteral(" id=\"header\"");

WriteLiteral(" class=\"bg-color0\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#top\"");

WriteLiteral("><img");

WriteLiteral(" src=\"example/logo.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral("></a>\r\n\r\n            <div");

WriteLiteral(" class=\"col-sm-12 mainmenu_wrap\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"main-menu-icon visible-xs\"");

WriteLiteral("><span></span><span></span><span></span></div>\r\n                <ul");

WriteLiteral(" id=\"mainmenu\"");

WriteLiteral(" class=\"nav menu sf-menu responsive-menu superfish\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#about\"");

WriteLiteral(">درباره ما</a>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#features\"");

WriteLiteral(">ویژگی ها</a>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#portfolio\"");

WriteLiteral(">نمونه کارها</a>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#sale\"");

WriteLiteral(">خدمات فوری</a>\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(">تماس با ما</a>\r\n                    </li>\r\n\r\n                </ul>\r\n            " +
"</div>\r\n\r\n        </div>\r\n    </div>\r\n</section>\r\n");

        }
    }
}
#pragma warning restore 1591
