#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<SoheilCMS.Models.IndexViewModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"flexslider\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"slides\"");

WriteLiteral(">\r\n                    <li>\r\n                        <img");

WriteLiteral(" class=\"fullwidthimage\"");

WriteLiteral(" alt=\"Full width image\"");

WriteAttribute("src", Tuple.Create("\r\n                              src=\"", 343), Tuple.Create("\"", 420)
            
            #line 17 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 380), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img6.jpg")
            
            #line default
            #line hidden
, 380), false)
);

WriteLiteral(">\r\n                    </li>\r\n                    <li>\r\n                        <" +
"img");

WriteLiteral(" class=\"fullwidthimage\"");

WriteLiteral(" alt=\"Full width image\"");

WriteAttribute("src", Tuple.Create(" \r\n                             src=\"", 551), Tuple.Create("\"", 628)
            
            #line 21 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 588), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img2.jpg")
            
            #line default
            #line hidden
, 588), false)
);

WriteLiteral(">\r\n                    </li>\r\n                    <li>\r\n                        <" +
"img");

WriteLiteral(" class=\"fullwidthimage\"");

WriteLiteral(" alt=\"Full width image\"");

WriteAttribute("src", Tuple.Create(" \r\n                             src=\"", 759), Tuple.Create("\"", 837)
            
            #line 25 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 796), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img10.jpg")
            
            #line default
            #line hidden
, 796), false)
);

WriteLiteral(">\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n        " +
"</div>\r\n    </div>\r\n</div>\r\n\r\n<section");

WriteLiteral(" id=\"land\"");

WriteLiteral(" class=\"title_section\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"single_teaser intro_images\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"introimg\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1220), Tuple.Create("\"", 1269)
            
            #line 39 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1226), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/land_services.jpg")
            
            #line default
            #line hidden
, 1226), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                    </div>\r\n                    <h3><a");

WriteLiteral(" href=\"#services\"");

WriteLiteral(">خدمات</a></h3>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"single_teaser intro_images\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"introimg\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1584), Tuple.Create("\"", 1634)
            
            #line 47 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1590), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/land_portfolio.jpg")
            
            #line default
            #line hidden
, 1590), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                    </div>\r\n                    <h3><a");

WriteLiteral(" href=\"#portfolio\"");

WriteLiteral(">نمونه کارها</a></h3>\r\n                </div>\r\n            </div>\r\n            <d" +
"iv");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"single_teaser intro_images\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"introimg\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1956), Tuple.Create("\"", 2002)
            
            #line 55 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1962), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/land_about.jpg")
            
            #line default
            #line hidden
, 1962), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                    </div>\r\n                    <h3><a");

WriteLiteral(" href=\"#about\"");

WriteLiteral(">درباره ما</a></h3>\r\n                </div>\r\n            </div>\r\n            <div" +
"");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"single_teaser intro_images\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"introimg\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2318), Tuple.Create("\"", 2366)
            
            #line 63 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2324), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/land_contact.jpg")
            
            #line default
            #line hidden
, 2324), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                    </div>\r\n                    <h3><a");

WriteLiteral(" href=\"#contact\"");

WriteLiteral(">تماس با ما</a></h3>\r\n                </div>\r\n            </div>\r\n        </div>\r" +
"\n    </div>\r\n</section>\r\n\r\n\r\n\r\n\r\n<div");

WriteLiteral(" id=\"box_wrap\"");

WriteLiteral(">\r\n\r\n    <section");

WriteLiteral(" id=\"about\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

            
            #line 78 "..\..\Views\Home\Index.cshtml"
       
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\Home\Index.cshtml"
          Html.RenderAction("ShowLastPostinHomePage","Blog"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n    </section>\r\n\r\n\r\n\r\n    <section");

WriteLiteral(" id=\"testimonials\"");

WriteLiteral(" class=\"parallax\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row to_fade\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"carousel slide widget_testimonials block\"");

WriteLiteral(" id=\"carousel-testimonials\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral(" href=\"#carousel-testimonials\"");

WriteLiteral(" class=\"carousel-control right\"");

WriteLiteral("></a>\r\n                        <a");

WriteLiteral(" data-slide=\"next\"");

WriteLiteral(" href=\"#carousel-testimonials\"");

WriteLiteral(" class=\"carousel-control left\"");

WriteLiteral("></a>\r\n                        <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"item active\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" class=\"carousel-introtext\"");

WriteLiteral(@">
                                    <span>
                                        تمام کار ها فقط با یک تماس
                                    </span>
                                </p>
                            </div>
                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" class=\"carousel-introtext\"");

WriteLiteral(@">
                                    <span>
                                        مجرب ترین متخصص ها
                                    </span>
                                </p>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </section>







    <section");

WriteLiteral(" id=\"progress\"");

WriteLiteral(" class=\"parallax color_section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">\r\n                        پیشینه ما\r\n                    </h2>\r\n                " +
"    <h3>پیشینه درخشان ما نشان از آینده ی درخشان ماست</h3>\r\n                </div" +
">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row to_fade\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"arctcle to_fade\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"single_teaser icons style2\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"icons_introimg image-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"rt-icon-user\"");

WriteLiteral(@"></i>
                            </div>
                            <h2>500+</h2>
                            <h3>

                                متخصص
                            </h3>

                        </div>
                    </div>
                </div>

                <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"arctcle\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"single_teaser icons style2\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"icons_introimg image-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"rt-icon-shopping-cart\"");

WriteLiteral(@"></i>
                            </div>
                            <h2>233</h2>
                            <h3>
                                خدمات انجام گرفته
                            </h3>

                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"arctcle\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"single_teaser icons style2\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"icons_introimg image-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"rt-icon-image\"");

WriteLiteral(@"></i>
                            </div>
                            <h2>350+</h2>
                            <h3>
                                نقاشی ساختمان
                            </h3>

                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"block col-sm-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"arctcle\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"single_teaser icons style2\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"icons_introimg image-icon\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"rt-icon-chat\"");

WriteLiteral(@"></i>
                            </div>
                            <h2>5000+</h2>
                            <h3>

                                تماس با ما
                            </h3>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>






    <section");

WriteLiteral(" id=\"partners\"");

WriteLiteral(" class=\"parallax color_section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row to_fade\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">مشتریان ما</h2>\r\n                    <p>فعلا مشتری نداریم اما انشالا در آینده مش" +
"تری زیاد داریم </p>\r\n                </div>\r\n            </div>\r\n\r\n            <" +
"div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"owl-carousel\"");

WriteLiteral(">\r\n\r\n\r\n\r\n                    </div>\r\n\r\n\r\n                </div>\r\n            </di" +
"v>\r\n\r\n        </div>\r\n    </section>\r\n\r\n\r\n    <section");

WriteLiteral(" id=\"portfolio\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">\r\n                        نمونه کارهای ما\r\n                    </h2>\r\n          " +
"          <h3>فعلا نمونه کاری نداریم این تصاویر فعلا الکیه</h3>\r\n               " +
" </div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"portfolio_wrapper\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"text-center filters col-sm-12\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" id=\"firtlable\"");

WriteLiteral(">\r\n                        <li><a");

WriteLiteral(" class=\"selected\"");

WriteLiteral(" data-filter=\"*\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">همه</a></li>\r\n                        <li><a");

WriteLiteral(" data-filter=\".graphicdesign\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">کابینت</a></li>\r\n                        <li><a");

WriteLiteral(" data-filter=\".photography\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">برق کاری</a></li>\r\n                        <li><a");

WriteLiteral(" data-filter=\".webdesign\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"\"");

WriteLiteral("> لوله کشی</a></li>\r\n                    </ul>\r\n                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                </div>\r\n                <!-- Items -->\r\n\r\n              " +
"  <ul");

WriteLiteral(" class=\"items-row row cols-3 portfolio firtlable clearfix isotope\"");

WriteLiteral(" id=\"portfolioContainer\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item graphicdesign webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8893), Tuple.Create("\"", 8939)
            
            #line 253 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 8899), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img1.jpg")
            
            #line default
            #line hidden
, 8899), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 9098), Tuple.Create("\"", 9145)
            
            #line 255 "..\..\Views\Home\Index.cshtml"
                       , Tuple.Create(Tuple.Create("", 9105), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img1.jpg")
            
            #line default
            #line hidden
, 9105), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single1.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"/gallery-single1.html\"");

WriteLiteral(">\r\n\r\n                                    نقاشی\r\n                                <" +
"/a>\r\n                            </h4>\r\n                        </div>\r\n        " +
"            </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item photography webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9881), Tuple.Create("\"", 9927)
            
            #line 274 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 9887), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img2.jpg")
            
            #line default
            #line hidden
, 9887), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 10086), Tuple.Create("\"", 10134)
            
            #line 276 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 10093), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img12.jpg")
            
            #line default
            #line hidden
, 10093), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single2.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single2.html\"");

WriteLiteral(">\r\n\r\n                                    بنایی\r\n                                <" +
"/a>\r\n                            </h4>\r\n                        </div>\r\n        " +
"            </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item photography webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10871), Tuple.Create("\"", 10917)
            
            #line 295 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 10877), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img3.jpg")
            
            #line default
            #line hidden
, 10877), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 11076), Tuple.Create("\"", 11123)
            
            #line 297 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 11083), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img3.jpg")
            
            #line default
            #line hidden
, 11083), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single3.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single3.html\"");

WriteLiteral(">\r\n\r\n                                    برق کشی\r\n                               " +
" </a>\r\n                            </h4>\r\n                        </div>\r\n      " +
"              </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11840), Tuple.Create("\"", 11886)
            
            #line 316 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 11846), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img4.jpg")
            
            #line default
            #line hidden
, 11846), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 12045), Tuple.Create("\"", 12092)
            
            #line 318 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 12052), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img4.jpg")
            
            #line default
            #line hidden
, 12052), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single4.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single4.html\"");

WriteLiteral(">\r\n\r\n                                    لوله کشی\r\n                              " +
"  </a>\r\n                            </h4>\r\n                        </div>\r\n     " +
"               </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item graphicdesign webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 12834), Tuple.Create("\"", 12880)
            
            #line 337 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 12840), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img5.jpg")
            
            #line default
            #line hidden
, 12840), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 13039), Tuple.Create("\"", 13086)
            
            #line 339 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 13046), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img5.jpg")
            
            #line default
            #line hidden
, 13046), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single5.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single5.html\"");

WriteLiteral(">\r\n\r\n                                    تاسیسات\r\n                               " +
" </a>\r\n                            </h4>\r\n                        </div>\r\n      " +
"              </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 13803), Tuple.Create("\"", 13849)
            
            #line 358 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13809), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img6.jpg")
            
            #line default
            #line hidden
, 13809), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 14008), Tuple.Create("\"", 14055)
            
            #line 360 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 14015), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img6.jpg")
            
            #line default
            #line hidden
, 14015), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single6.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single6.html\"");

WriteLiteral(">\r\n\r\n                                    کابینت\r\n                                " +
"</a>\r\n                            </h4>\r\n                        </div>\r\n       " +
"             </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item photography webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 14793), Tuple.Create("\"", 14839)
            
            #line 379 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 14799), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img7.jpg")
            
            #line default
            #line hidden
, 14799), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 14998), Tuple.Create("\"", 15046)
            
            #line 381 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 15005), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img11.jpg")
            
            #line default
            #line hidden
, 15005), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single7.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single7.html\"");

WriteLiteral(">\r\n\r\n                                    طراحی داخلی\r\n                           " +
"     </a>\r\n                            </h4>\r\n                        </div>\r\n  " +
"                  </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item graphicdesign webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 15791), Tuple.Create("\"", 15837)
            
            #line 400 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 15797), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img8.jpg")
            
            #line default
            #line hidden
, 15797), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 15996), Tuple.Create("\"", 16043)
            
            #line 402 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 16003), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img8.jpg")
            
            #line default
            #line hidden
, 16003), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single8.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single8.html\"");

WriteLiteral(">\r\n\r\n                                    آث میلان\r\n                              " +
"  </a>\r\n                            </h4>\r\n                        </div>\r\n     " +
"               </li>\r\n\r\n                    <li");

WriteLiteral(" class=\"item col-sm-6 col-md-4 isotope-item graphicdesign webdesign\"");

WriteLiteral(">\r\n\r\n                        <!-- Image  -->\r\n\r\n                        <div");

WriteLiteral(" class=\"portfolio_item_image\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 16785), Tuple.Create("\"", 16831)
            
            #line 421 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 16791), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img9.jpg")
            
            #line default
            #line hidden
, 16791), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"portfolio_links\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"p-view prettyPhoto\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" rel=\"prettyPhoto[pp_gal]\"");

WriteAttribute("href", Tuple.Create(" href=\"", 16990), Tuple.Create("\"", 17037)
            
            #line 423 "..\..\Views\Home\Index.cshtml"
                      , Tuple.Create(Tuple.Create("", 16997), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img9.jpg")
            
            #line default
            #line hidden
, 16997), false)
);

WriteLiteral("></a>\r\n                                <a");

WriteLiteral(" class=\"p-link\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" href=\"./gallery-single9.html\"");

WriteLiteral("></a>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"item_title\"");

WriteLiteral(">\r\n                            <h4>\r\n                                <a");

WriteLiteral(" href=\"./gallery-single9.html\"");

WriteLiteral(@">

                                    ایتالیا
                                </a>
                            </h4>
                        </div>
                    </li>

                </ul>
            </div> <!--eof portfolio_wrapper-->

            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"text-center loadmore\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"./gallery.html\"");

WriteLiteral(" class=\"theme_btn inverse\"");

WriteLiteral(">\r\n                            مشاهده بیشتر\r\n                        </a>\r\n      " +
"              </p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n" +
"    </section>\r\n\r\n\r\n    <section");

WriteLiteral(" id=\"sale\"");

WriteLiteral(" class=\"grey_section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row to_fade\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">خدمات فوری</h2>\r\n                    <p>خدماتی که در کمترین زمان به شما ارائه می" +
" دهیم </p>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                    <h3>\r\n                        پیشنهاد جدید\r\n              " +
"      </h3>\r\n\r\n                    <!-- Horizontal Slider -->\r\n\r\n               " +
"     <div");

WriteLiteral(" class=\"horizontal_slider_list_wrapper related-posts\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"horizontal_slider\"");

WriteLiteral(" dir=ltr");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"horizontal_slider_list\"");

WriteLiteral(">\r\n                                <li>\r\n                                    <art" +
"icle");

WriteLiteral(" class=\"post format-standard\"");

WriteLiteral(">\r\n                                        <header");

WriteLiteral(" class=\"entry-header\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"entry-thumbnail\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 19081), Tuple.Create("\"", 19127)
            
            #line 476 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 19087), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img1.jpg")
            
            #line default
            #line hidden
, 19087), false)
);

WriteLiteral(" class=\"post-image\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </header>\r\n                                        <!-- .entry-hea" +
"der -->\r\n\r\n                                        <div");

WriteLiteral(" class=\"entry-content\"");

WriteLiteral(">\r\n                                            <h2");

WriteLiteral(" class=\"entry-title\"");

WriteLiteral(@">

                                                نمای ساختمان
                                            </h2>

                                            <p>نمای ساختمان شما</p>

                                        </div>
                                        <!-- .entry-content -->
                                        <div");

WriteLiteral(" class=\"entry-share\"");

WriteLiteral(">\r\n                                            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"socialico-facebook\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Facebook\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-twitter\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Twitter\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-google\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Google\"");

WriteLiteral(@">#</a>
                                            </p>
                                        </div>
                                        <!-- .entry-share -->
                                    </article>

                                </li>

                                <li>
                                    <article");

WriteLiteral(" class=\"post format-standard border-color2\"");

WriteLiteral(">\r\n                                        <header");

WriteLiteral(" class=\"entry-header\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"entry-thumbnail\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 20807), Tuple.Create("\"", 20853)
            
            #line 507 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 20813), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img2.jpg")
            
            #line default
            #line hidden
, 20813), false)
);

WriteLiteral(" class=\"post-image\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </header>\r\n                                        <!-- .entry-hea" +
"der -->\r\n\r\n                                        <div");

WriteLiteral(" class=\"entry-content\"");

WriteLiteral(">\r\n                                            <h2");

WriteLiteral(" class=\"entry-title\"");

WriteLiteral(@">
                                                برق کشی ساختمان
                                            </h2>

                                            <p>برق کشی ساختمان شما</p>

                                        </div>
                                        <!-- .entry-content -->
                                        <div");

WriteLiteral(" class=\"entry-share\"");

WriteLiteral(">\r\n                                            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"socialico-facebook\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Facebook\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-twitter\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Twitter\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-google\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Google\"");

WriteLiteral(@">#</a>
                                            </p>
                                        </div>
                                        <!-- .entry-share -->
                                    </article>

                                </li>

                                <li>
                                    <article");

WriteLiteral(" class=\"post format-standard border-color3\"");

WriteLiteral(">\r\n                                        <header");

WriteLiteral(" class=\"entry-header\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"entry-thumbnail\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 22537), Tuple.Create("\"", 22583)
            
            #line 537 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 22543), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img3.jpg")
            
            #line default
            #line hidden
, 22543), false)
);

WriteLiteral(" class=\"post-image\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </header>\r\n                                        <!-- .entry-hea" +
"der -->\r\n\r\n                                        <div");

WriteLiteral(" class=\"entry-content\"");

WriteLiteral(">\r\n                                            <h2");

WriteLiteral(" class=\"entry-title\"");

WriteLiteral(@">
                                                لوله کشی
                                            </h2>

                                            <p>لوله هاتون ترکیده؟ به ما زنگ بزنید</p>

                                        </div>
                                        <!-- .entry-content -->
                                        <div");

WriteLiteral(" class=\"entry-share\"");

WriteLiteral(">\r\n                                            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"socialico-facebook\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Facebook\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-twitter\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Twitter\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-google\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Google\"");

WriteLiteral(@">#</a>
                                            </p>
                                        </div>
                                        <!-- .entry-share -->
                                    </article>

                                </li>

                                <li>
                                    <article");

WriteLiteral(" class=\"post format-standard\"");

WriteLiteral(">\r\n                                        <header");

WriteLiteral(" class=\"entry-header\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"entry-thumbnail\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 24261), Tuple.Create("\"", 24307)
            
            #line 567 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 24267), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img4.jpg")
            
            #line default
            #line hidden
, 24267), false)
);

WriteLiteral(" class=\"post-image\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </header>\r\n                                        <!-- .entry-hea" +
"der -->\r\n\r\n                                        <div");

WriteLiteral(" class=\"entry-content\"");

WriteLiteral(">\r\n                                            <h2");

WriteLiteral(" class=\"entry-title\"");

WriteLiteral(@">
                                                تاسیسات ساختمان
                                            </h2>

                                            <p>تاسیسات؟ به ما زنگ بزنید</p>

                                        </div>
                                        <!-- .entry-content -->
                                        <div");

WriteLiteral(" class=\"entry-share\"");

WriteLiteral(">\r\n                                            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"socialico-facebook\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Facebook\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-twitter\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Twitter\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-google\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Google\"");

WriteLiteral(@">#</a>
                                            </p>
                                        </div>
                                        <!-- .entry-share -->
                                    </article>

                                </li>

                                <li>
                                    <article");

WriteLiteral(" class=\"post format-standard border-color2\"");

WriteLiteral(">\r\n                                        <header");

WriteLiteral(" class=\"entry-header\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"entry-thumbnail\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 25996), Tuple.Create("\"", 26042)
            
            #line 597 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 26002), Tuple.Create<System.Object, System.Int32>(Url.Content("~/example/intro_img5.jpg")
            
            #line default
            #line hidden
, 26002), false)
);

WriteLiteral(" class=\"post-image\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                                            </div>\r\n                          " +
"              </header>\r\n                                        <!-- .entry-hea" +
"der -->\r\n\r\n                                        <div");

WriteLiteral(" class=\"entry-content\"");

WriteLiteral(">\r\n                                            <h2");

WriteLiteral(" class=\"entry-title\"");

WriteLiteral(@">
                                                تعمیرات منزل
                                            </h2>

                                            <p>انجام هر نوع تعمیرات منزل</p>

                                        </div>
                                        <!-- .entry-content -->
                                        <div");

WriteLiteral(" class=\"entry-share\"");

WriteLiteral(">\r\n                                            <p");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"socialico-facebook\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Facebook\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-twitter\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Twitter\"");

WriteLiteral(">#</a>\r\n                                                <a");

WriteLiteral(" class=\"socialico-google\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Google\"");

WriteLiteral(@">#</a>
                                            </p>
                                        </div>
                                        <!-- .entry-share -->
                                    </article>

                                </li>



                            </ul>
                        </div>
                    </div>

                    <!--EOF Horizontal Slider -->

                </div>
            </div>

        </div>
    </section>

    <section");

WriteLiteral(" id=\"info\"");

WriteLiteral(" class=\"color_section parallax\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h5");

WriteLiteral(" class=\"contact-phone to_fade\"");

WriteLiteral(">09901149011</h5>\r\n                    <h2");

WriteLiteral(" class=\"contact-email to_fade\"");

WriteLiteral("><span><a");

WriteLiteral(" href=\"Grayco.ir\"");

WriteLiteral(">Grayco.ir</a></span></h2>\r\n                    <p");

WriteLiteral(" class=\"contact-address to_fade\"");

WriteLiteral(">تهران</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </sec" +
"tion>\r\n\r\n\r\n    <section");

WriteLiteral(" id=\"contact\"");

WriteLiteral(" class=\"dark_section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12 text-center\"");

WriteLiteral(">\r\n                    <h2");

WriteLiteral(" class=\"block-header\"");

WriteLiteral(">تماس با ما</h2>\r\n                    <h3>در کمترین زمان ممکن با شما تماس میگیریم" +
"</h3>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"contact-form\"");

WriteLiteral(">\r\n                        <form");

WriteLiteral(" class=\"contact-form\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" action=\"/\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"contact-form-name\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"name\"");

WriteLiteral(">نام<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(">*</span></label>\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" aria-required=\"true\"");

WriteLiteral(" size=\"30\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" id=\"name\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"نام\"");

WriteLiteral(">\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"contact-form-email\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"email\"");

WriteLiteral(">ایمیل<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(">*</span></label>\r\n                                <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" aria-required=\"true\"");

WriteLiteral(" size=\"30\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"ایمیل\"");

WriteLiteral(">\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"contact-form-message\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"message\"");

WriteLiteral(">پیام</label>\r\n                                <textarea");

WriteLiteral(" aria-required=\"true\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" cols=\"45\"");

WriteLiteral(" name=\"message\"");

WriteLiteral(" id=\"message\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"پیام\"");

WriteLiteral("></textarea>\r\n                            </p>\r\n                            <p");

WriteLiteral(" class=\"contact-form-submit text-center vertical-margin-60\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ارسال\"");

WriteLiteral(" id=\"contact_form_submit\"");

WriteLiteral(" name=\"contact_submit\"");

WriteLiteral(" class=\"theme_btn inverse\"");

WriteLiteral(">\r\n                            </p>\r\n                        </form>\r\n           " +
"         </div>\r\n                </div>\r\n\r\n            </div>\r\n        </div>\r\n " +
"   </section>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
