#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WorkSamplesPlugin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WorkSamples/Views/UserWorkCategory/GetBaseCategory.cshtml")]
    public partial class _Areas_WorkSamples_Views_UserWorkCategory_GetBaseCategory_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<WorkSample.Contracts.WorkCategoryBaseDTO>>
    {
        public _Areas_WorkSamples_Views_UserWorkCategory_GetBaseCategory_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" id=\"firtlable\"");

WriteLiteral(">\r\n    <li><a");

WriteLiteral(" class=\"selected\"");

WriteLiteral(" data-filter=\"*\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">همه</a></li>\r\n");

            
            #line 4 "..\..\Areas\WorkSamples\Views\UserWorkCategory\GetBaseCategory.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\WorkSamples\Views\UserWorkCategory\GetBaseCategory.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li><a");

WriteLiteral(" data-filter=\".");

            
            #line 6 "..\..\Areas\WorkSamples\Views\UserWorkCategory\GetBaseCategory.cshtml"
                        Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">");

            
            #line 6 "..\..\Areas\WorkSamples\Views\UserWorkCategory\GetBaseCategory.cshtml"
                                                      Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 7 "..\..\Areas\WorkSamples\Views\UserWorkCategory\GetBaseCategory.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
