#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SoheilCMS;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Home/AdminMenu.cshtml")]
    public partial class _Areas_Admin_Views_Home_AdminMenu_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<PluginBase.IPluginBase>>
    {
        public _Areas_Admin_Views_Home_AdminMenu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"panel1\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" data-panel=\"panel1\"");

WriteLiteral(" class=\"panel-button\"");

WriteLiteral(" style=\"margin:0 30px 0 auto;\"");

WriteLiteral("></span>\r\n    <div");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(">\r\n        <ul>\r\n            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 251), Tuple.Create("\"", 285)
            
            #line 8 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
, Tuple.Create(Tuple.Create("", 258), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 258), false)
);

WriteLiteral(">خانه</a>\r\n            </li>\r\n            <li>\r\n                <div>نوشته ها</di" +
"v>\r\n                <ul>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 419), Tuple.Create("\"", 475)
            
            #line 13 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
, Tuple.Create(Tuple.Create("", 426), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "tag", new {Area = "Admin"})
            
            #line default
            #line hidden
, 426), false)
);

WriteLiteral(">برچسب ها</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 522), Tuple.Create("\"", 583)
            
            #line 14 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
, Tuple.Create(Tuple.Create("", 529), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "Category", new {Area = "Admin"})
            
            #line default
            #line hidden
, 529), false)
);

WriteLiteral(">دسته ها</a></li>\r\n                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 629), Tuple.Create("\"", 686)
            
            #line 15 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
, Tuple.Create(Tuple.Create("", 636), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "Post", new {Area = "Admin"})
            
            #line default
            #line hidden
, 636), false)
);

WriteLiteral(">نوشته ها</a></li>\r\n                </ul>\r\n            </li>\r\n\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div>");

            
            #line 22 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
                    Write(item.GetMenuItem(Request.RequestContext).Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <ul>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
                         foreach (var child in item.GetChildMenuItem(Request.RequestContext))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1091), Tuple.Create("\"", 1108)
            
            #line 26 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1098), Tuple.Create<System.Object, System.Int32>(child.Url
            
            #line default
            #line hidden
, 1098), false)
);

WriteLiteral(">");

            
            #line 26 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
                                                Write(child.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 27 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
                           
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </li>\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\Home\AdminMenu.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <div>Quis Porttitor</div>\r\n                <ul>" +
"\r\n                    <li><a");

WriteLiteral(" href=\"?21\"");

WriteLiteral(">Finibus Bonorum</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"?22\"");

WriteLiteral(">Sed ut</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"?23\"");

WriteLiteral(">Neque porro</a></li>\r\n                </ul>\r\n            </li>\r\n            <li>" +
"\r\n                <div>Odio Ac</div>\r\n                <ul>\r\n                    " +
"<li><a");

WriteLiteral(" href=\"?31\"");

WriteLiteral(">Minima veniam</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"?32\"");

WriteLiteral(">Voluptate velit</a></li>\r\n                </ul>\r\n            </li>\r\n            " +
"<li>\r\n                <a");

WriteLiteral(" href=\"?4\"");

WriteLiteral(">Sapien quam</a>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n</div>\r\n    ");

        }
    }
}
#pragma warning restore 1591
